export { DashboardIcon } from './DashboardIcon';
export { TimelineIcon } from './TimelineIcon';
export { VaultIcon } from './VaultIcon';
export { CrmIcon } from './CrmIcon';
export { CalendarIcon } from './CalendarIcon';
export { SupportIcon } from './SupportIcon';
export { SettingsIcon } from './SettingsIcon';
export { ThemeIcon } from './ThemeIcon';
export { DownloadIcon } from './DownloadIcon';
export { ChevronLeftIcon } from './ChevronLeftIcon';
export { ChevronRightIcon } from './ChevronRightIcon';
export { EventzrLogo } from './EventzrLogo';
export { EventzrLogoCollapsed } from './EventzrLogoCollapsed';
export { MyZarsIcon } from './MyZarsIcon';
export { MyRfpsIcon } from './MyRfpsIcon';
export { WhatsAppIcon } from './WhatsAppIcon';
export { InstagramIcon } from './InstagramIcon';
export { FacebookIcon } from './FacebookIcon';
export { TwitterXIcon } from './TwitterXIcon';
export { TelegramIcon } from './TelegramIcon';
export { default as HomeIcon } from './HomeIcon';
export { default as UserPlusIcon } from './UserPlusIcon';
export { default as BellIcon } from './BellIcon';
export { default as BoxIcon } from './BoxIcon';
export { default as HeartIcon } from './HeartIcon';
export { default as ShoppingBagIcon } from './ShoppingBagIcon';
export { default as ShoppingBagOnHoldIcon } from './ShoppingBagOnHoldIcon';
export { default as DeliveredIcon } from './DeliveredIcon';
export { default as CheckIcon } from './CheckIcon';
export { default as UserSwitchIcon } from './UserSwitchIcon';
export { default as GlobalIcon } from './GlobalIcon';
export { default as DollarIcon } from './DollarIcon';
export { default as ClockIcon } from './ClockIcon';
export { default as Home2Icon } from './Home2Icon';
export { default as Users3Icon } from './Users3Icon';
export { default as BriefcaseIcon } from './BriefcaseIcon';
export { default as NewsIcon } from './NewsIcon';
export { default as CallIcon } from './CallIcon';
export { default as PhoneIcon } from './PhoneIcon';
export { default as JobSearchIcon } from './JobSearchIcon';
export { default as AiChipIcon } from './AiChipIcon';
export { default as MagicWandIcon } from './MagicWandIcon';
export { default as BuildingIcon } from './BuildingIcon';

// Unified Icon component
export { Icon, type IconName } from './Icon';